name: Deploy
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Release type (patch / minor / major)
        required: false
        default: patch
      release_notes:
        description: Human-readable description of changes introduced by this release.
        required: false
      include_commit_messages:
        description: Include commit messages since last release? (true / false)
        required: false
        default: "true"

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.bump-version.outputs.new-version }}
      tarball-path: ${{ steps.pack-tarball.outputs.tarball-path }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
      - name: Bump version
        id: bump-version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "::set-output name=new-version::$(npm version ${{ github.event.inputs.release_type }})"
          git push --follow-tags
      - name: Install, build and test
        run: npm ci && npm run build && npm test
      - name: Pack tarball
        id: pack-tarball
        run: echo "::set-output name=tarball-path::$(npm pack -s)"
      - name: Upload tarball
        uses: actions/upload-artifact@v2
        with:
          name: tarball
          path: ${{ steps.pack-tarball.outputs.tarball-path }}
          retention-days: 1

  publish-to-npm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - name: Download tarball
        uses: actions/download-artifact@v2
        with:
          name: tarball
      - run: npm publish ${{ needs.build.outputs.tarball-path }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-docker-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download tarball
        uses: actions/download-artifact@v2
        with:
          name: tarball
      - name: Build image
        id: build-image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: ${{ needs.build.outputs.tarball-path }}
      - name: Test image
        run: |
          docker cp . ${{ steps.build-image.outputs.digest }}:/user-project
          run: docker run ${{ steps.build-image.outputs.digest }} /user-project
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: ${{ needs.build.outputs.tarball-path }}
          push: true
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.build.outputs.new-version }},
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
  
  github-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate release notes
        run: |
          echo ${{ github.event.inputs.release_notes }} >> release-notes.md
          if [[ ${{ github.event.inputs.include_commit_messages }} == true ]]; then
            chmod +x .github/generate-release-notes.sh;
            .github/generate-release-notes.sh release-notes.md;
          fi
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          body_path: release-notes.md
          tag_name: ${{ needs.build.outputs.new-version }}